#!/bin/sh
# A-B harness wrapper — the standing behavior-identity gate for sim refactors.
# Creates a git worktree at $BASE (arg, default 869e83b — the reviewed
# pre-optimization build), runs tools/ab_state_dump.gd at BOTH commits (the
# current HEAD harness is copied into the worktree so both runs share one
# harness version), diffs the dumps and compares against the recorded
# sanctioned baseline in tests/fixtures/ab/evidence.txt:
#   identical dumps            → exit 0 (IDENTICAL)
#   diff sha == recorded sha   → exit 0 (SANCTIONED_MATCH — the I5 f64 class,
#                                deterministic, sha-pinned)
#   anything else              → exit 1 (FAIL — a real behavior change)
# Usage: tools/ab_test.sh [BASE_COMMIT]
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 1
BASE="${1:-869e83b}"
EVIDENCE="tests/fixtures/ab/evidence.txt"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git worktree add -q "$WORK/base" "$BASE" || exit 1
cp tools/ab_state_dump.gd "$WORK/base/tools/ab_state_dump.gd"

GODOT="${GODOT:-$HOME/.local/bin/godot}"

echo "ab: dumping HEAD (current tree)..."
"$GODOT" --headless -s tools/ab_state_dump.gd > "$WORK/head.txt" || exit 1
echo "ab: dumping base $BASE..."
( cd "$WORK/base" && "$GODOT" --headless -s tools/ab_state_dump.gd ) > "$WORK/base.txt" || exit 1

git worktree remove --force "$WORK/base" 2>/dev/null

BASE_SHA="$(sha256sum "$WORK/base.txt" | cut -d' ' -f1)"
HEAD_SHA="$(sha256sum "$WORK/head.txt" | cut -d' ' -f1)"
diff "$WORK/base.txt" "$WORK/head.txt" > "$WORK/ab.diff"
DIFF_LINES="$(wc -l < "$WORK/ab.diff" | tr -d ' ')"
DIFF_SHA=""
if [ "$DIFF_LINES" -gt 0 ]; then
	DIFF_SHA="$(sha256sum "$WORK/ab.diff" | cut -d' ' -f1)"
fi

RECORDED_SHA=""
if [ -f "$EVIDENCE" ]; then
	RECORDED_SHA="$(sed -n 's/^sanctioned_diff_sha256=//p' "$EVIDENCE" | head -1)"
fi

VERDICT="FAIL"
if [ "$DIFF_LINES" -eq 0 ]; then
	VERDICT="IDENTICAL"
elif [ -z "$RECORDED_SHA" ]; then
	# first run for this harness version: establish the recorded baseline —
	# a human must eyeball the diff (tests/fixtures/ab/last_diff.txt) against
	# PARITY-M2.md §17's sanctioned class before trusting it
	VERDICT="RECORD"
elif [ -n "$DIFF_SHA" ] && [ "$DIFF_SHA" = "$RECORDED_SHA" ]; then
	VERDICT="SANCTIONED_MATCH"
fi

echo "ab: base=$BASE_SHA"
echo "ab: head=$HEAD_SHA"
echo "ab: diff_lines=$DIFF_LINES"
if [ "$VERDICT" = "FAIL" ]; then
	# fail-CLOSED on the evidence file (M2 final-review carry-forward): the
	# write used to sit ABOVE this check, so a failing run clobbered
	# sanctioned_diff_sha256 with its own diff sha — and the SECOND failing
	# run then read its own sha back and laundered into SANCTIONED_MATCH
	# (exit 0). On FAIL nothing in tests/fixtures/ab/ is touched; the failing
	# diff lands in /tmp for eyeballing. tools/test_ab.sh pins the failure path.
	echo "AB_TEST_FAIL: diff sha $DIFF_SHA does not match the recorded sanctioned diff (see $EVIDENCE)"
	cp "$WORK/ab.diff" /tmp/ab_test_fail.diff 2>/dev/null || true
	exit 1
fi

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
HEAD_COMMIT="$(git rev-parse HEAD)"
{
	echo "# A-B evidence — generated by tools/ab_test.sh; see PARITY-M2.md §17"
	echo "generated=$STAMP"
	echo "base_commit=$BASE"
	echo "head_commit=$HEAD_COMMIT"
	echo "base_dump_sha256=$BASE_SHA"
	echo "head_dump_sha256=$HEAD_SHA"
	echo "diff_lines=$DIFF_LINES"
	echo "sanctioned_diff_sha256=$DIFF_SHA"
	echo "verdict=$VERDICT"
} > "$EVIDENCE"
cp "$WORK/ab.diff" tests/fixtures/ab/last_diff.txt 2>/dev/null || true
echo "AB_TEST_OK verdict=$VERDICT"
exit 0
